# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codewar', '0002_auto_20170828_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
