# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bem',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
