# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0002_auto_20170627_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
