# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0004_auto_20170630_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
        migrations.AddField(
            model_name='report',
            name='week',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
