# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0006_developer_vote_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('coding', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='quiz',
            field=models.ManyToManyField(blank=True, default=None, to='windows.Quiz'),
        ),
    ]
