# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0008_quiz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='scores',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
